import { useState } from 'react';
import { CalendarOutlined, CheckCircleOutlined, GiftOutlined, HeartOutlined, MessageOutlined, PauseCircleOutlined, PlusOutlined, SendOutlined, TeamOutlined } from '@ant-design/icons';
import { App, Breadcrumb, Button, Card, Col, DatePicker, Descriptions, Flex, Form, Input, InputNumber, Progress, Row, Select, Space, Statistic, Steps, Switch, Table, Tag, Timeline, Typography } from 'antd';
import { ListPageHeading, SearchField, SearchPanel } from '../../../shared/ui/ListPage';

type CarePageMode = 'plans' | 'plan-create' | 'plan-detail' | 'records' | 'templates' | 'types';

export function CarePages({ mode, onNavigate }: { mode: CarePageMode; onNavigate: (page: string) => void }) {
  if (mode === 'plan-create') return <CarePlanForm onBack={() => onNavigate('care-plans')} onDone={() => onNavigate('care-plan-detail')} />;
  if (mode === 'plan-detail') return <CarePlanDetail onBack={() => onNavigate('care-plans')} />;
  if (mode === 'templates') return <CareTemplates />;
  if (mode === 'records') return <CareRecords />;
  if (mode === 'types') return <CareTypes />;
  return <CarePlanList onNavigate={onNavigate} />;
}

const plans = [
  { id: 1, name: '八月员工生日关怀', type: '生日关怀', scope: '本月生日员工 36 人', date: '2026-08-01 至 08-31', status: '执行中', reached: 28 },
  { id: 2, name: '五周年入职纪念计划', type: '入职周年', scope: '司龄满五年员工 18 人', date: '2026-08-20', status: '待执行', reached: 0 },
  { id: 3, name: '中秋节全员关怀', type: '节日关怀', scope: '全体员工 1,286 人', date: '2026-09-25', status: '草稿', reached: 0 },
  { id: 4, name: '新员工首周欢迎', type: '入职欢迎', scope: '当月新员工 24 人', date: '持续执行', status: '已暂停', reached: 112 },
];

function CarePlanList({ onNavigate }: { onNavigate: (page: string) => void }) {
  const { message } = App.useApp();
  return <div className="page-stack"><ListPageHeading paths={['人文关怀','关怀运营','关怀计划']} title="关怀计划" subtitle="围绕员工关键时刻规划关怀内容与权益。"/><SearchPanel fieldCount={5} onSearch={()=>message.success('查询完成')} onReset={()=>undefined}><SearchField label="计划名称"><Input placeholder="请输入计划名称"/></SearchField><SearchField label="关怀类型"><Select placeholder="全部类型" options={['生日关怀','入职周年','节日关怀','入职欢迎'].map(value=>({value,label:value}))}/></SearchField><SearchField label="执行状态"><Select placeholder="全部状态" options={['草稿','待执行','执行中','已完成','已暂停'].map(value=>({value,label:value}))}/></SearchField><SearchField label="负责部门"><Select placeholder="全部部门" options={[{value:'员工体验部',label:'员工体验部'},{value:'人力资源部',label:'人力资源部'}]}/></SearchField><SearchField label="执行日期"><DatePicker.RangePicker style={{width:'100%'}}/></SearchField></SearchPanel><Card><div className="table-toolbar"><Space><Button type="primary" icon={<PlusOutlined/>} onClick={()=>onNavigate('care-plan-create')}>新建计划</Button><Button onClick={()=>message.info('请选择需要启用的计划')}>批量启用</Button><Button danger onClick={()=>message.warning('暂停前需确认影响范围')}>批量暂停</Button></Space></div><Table rowKey="id" rowSelection={{}} dataSource={plans} columns={[{title:'计划名称',dataIndex:'name',render:value=><Button type="link" className="inline-link" onClick={()=>onNavigate('care-plan-detail')}>{value}</Button>},{title:'关怀类型',dataIndex:'type'},{title:'关怀对象',dataIndex:'scope'},{title:'执行时间',dataIndex:'date'},{title:'触达人数',dataIndex:'reached',align:'right'},{title:'状态',dataIndex:'status',render:value=><Tag color={value==='执行中'?'processing':value==='待执行'?'warning':value==='已暂停'?'error':'default'}>{value}</Tag>},{title:'操作',render:(_,record)=><Space><Button type="link" onClick={()=>onNavigate('care-plan-detail')}>详情</Button><Button type="link">复制</Button>{record.status==='执行中'&&<Button type="link" danger>暂停</Button>}</Space>}]} /></Card></div>;
}

function CarePlanForm({ onBack, onDone }: { onBack: () => void; onDone: () => void }) {
  const { message } = App.useApp();
  const [form] = Form.useForm();
  const [current, setCurrent] = useState(0);
  const [careType, setCareType] = useState('生日关怀');
  const next = async () => { try { await form.validateFields(); setCurrent(value => value + 1); } catch { message.error('请先完成当前步骤的必填信息'); } };
  const publish = async () => { try { await form.validateFields(); message.success('关怀计划已发布'); onDone(); } catch { message.error('请先设置执行时间'); } };
  const stepContent = current === 0 ? <Card title="选择关怀类型"><Form.Item label="计划名称" name="name" rules={[{required:true,message:'请输入计划名称'}]} extra="名称用于运营识别，不会发送给员工"><Input placeholder="例如：九月员工生日关怀"/></Form.Item><Form.Item label="关怀类型" name="type" rules={[{required:true}]} extra="选择后将联动人员规则和推荐模板"><Select value={careType} onChange={setCareType} options={['生日关怀','入职周年','节日关怀','入职欢迎','特殊慰问'].map(value=>({value,label:value}))}/></Form.Item></Card> : current === 1 ? <Card title="设置关怀对象"><Row gutter={16}><Col span={12}><Form.Item label={careType==='生日关怀'?'生日范围':'人员范围'} name="range" rules={[{required:true}]} extra="系统按员工档案动态计算"><Select options={[{value:'本月生日员工',label:'本月生日员工'},{value:'下月生日员工',label:'下月生日员工'},{value:'指定员工',label:'指定员工'}]}/></Form.Item></Col><Col span={12}><Form.Item label="所属部门" name="departments" extra="留空表示全部部门"><Select mode="multiple" options={['产品中心','研发中心','营销中心','职能中心'].map(value=>({value,label:value}))}/></Form.Item></Col></Row><Card size="small"><Flex justify="space-between"><Typography.Text>预计覆盖人数</Typography.Text><Typography.Title level={3} style={{margin:0,fontWeight:400}}>36 人</Typography.Title></Flex></Card></Card> : current === 2 ? <Card title="配置关怀内容和权益"><Form.Item label="消息模板" name="template" rules={[{required:true}]} extra="消息发送前可在下一步预览"><Select options={[{value:'温暖生日祝福',label:'温暖生日祝福'},{value:'简洁生日祝福',label:'简洁生日祝福'}]}/></Form.Item><Form.Item label="祝福补充文案" name="message" extra="最多 200 字，将追加在模板正文后"><Input.TextArea rows={3} maxLength={200} showCount/></Form.Item><Row gutter={16}><Col span={12}><Form.Item label="发放权益" name="benefit"><Select allowClear options={[{value:'生日蛋糕券',label:'生日蛋糕券 · ¥100'},{value:'悦享积分',label:'悦享积分 · 1,000 分'}]}/></Form.Item></Col><Col span={12}><Form.Item label="单人预算" name="budget" initialValue={100}><InputNumber min={0} addonBefore="¥" style={{width:'100%'}}/></Form.Item></Col></Row></Card> : <Card title="设置执行时间并确认"><Form.Item label="执行时间" name="executeAt" rules={[{required:true}]} extra="通知和权益将在该时间开始发放"><DatePicker showTime style={{width:'100%'}}/></Form.Item><Form.Item label="发送通知" name="notice" valuePropName="checked" initialValue><Switch checkedChildren="发送" unCheckedChildren="不发送"/></Form.Item><Card size="small" className="care-confirm-card"><Descriptions column={2} items={[{label:'关怀类型',children:careType},{label:'预计人数',children:'36 人'},{label:'单人预算',children:'¥100.00'},{label:'预计总额',children:<Typography.Text type="danger">¥3,600.00</Typography.Text>}]} /></Card></Card>;
  return <div className="page-stack advanced-form-page"><Breadcrumb separator=">" items={[{title:'人文关怀'},{title:'关怀计划'},{title:'新建计划'}]}/><Flex align="baseline" gap={16}><Typography.Title level={1}>新建关怀计划</Typography.Title><Typography.Text type="secondary">按步骤配置对象、内容和执行规则。</Typography.Text></Flex><Card><Steps current={current} items={['选择类型','设置对象','配置内容','确认发布'].map(title=>({title}))}/></Card><Form form={form} layout="horizontal" className="edit-form" preserve initialValues={{type:'生日关怀'}}>{stepContent}<div className="sticky-form-actions"><Space>{current===3?<Button type="primary" onClick={publish}>确认发布</Button>:<Button type="primary" onClick={next}>下一步</Button>}{current>0&&<Button onClick={()=>setCurrent(value=>value-1)}>上一步</Button>}<Button onClick={onBack}>取消</Button></Space></div></Form></div>;
}

function CarePlanDetail({ onBack }: { onBack: () => void }) {
  const { message } = App.useApp();
  return <div className="page-stack order-detail-page"><Breadcrumb className="detail-breadcrumb" separator=">" items={[{title:'人文关怀'},{title:<Button type="link" className="breadcrumb-link" onClick={onBack}>关怀计划</Button>},{title:'八月员工生日关怀'}]}/><Flex className="detail-title-row" justify="space-between" align="center" gap={16} wrap="wrap"><div><Flex align="center" gap={12}><Typography.Title level={1}>八月员工生日关怀</Typography.Title><Tag color="processing">执行中</Tag></Flex><Typography.Text type="secondary">计划编号 GH-2026-081 · 负责人：苏然</Typography.Text></div><Space><Button type="primary" icon={<SendOutlined/>} onClick={()=>message.success('已补发通知')}>补发通知</Button><Button icon={<PauseCircleOutlined/>}>暂停计划</Button><Button>复制计划</Button></Space></Flex><Row gutter={[16,16]}>{[{title:'计划人数',value:36,icon:<TeamOutlined/>},{title:'已触达人数',value:28,icon:<MessageOutlined/>},{title:'权益领取人数',value:21,icon:<GiftOutlined/>},{title:'领取率',value:75,suffix:'%',icon:<CheckCircleOutlined/>}].map(item=><Col xs={24} sm={12} xl={6} key={item.title}><Card className="compact-stat-card"><Flex justify="space-between" align="center"><Statistic title={item.title} value={item.value} suffix={item.suffix} valueStyle={{fontWeight:400}}/><div className="compact-stat-logo purple">{item.icon}</div></Flex></Card></Col>)}</Row><Card title="计划信息"><Descriptions column={3} items={[{label:'关怀类型',children:'生日关怀'},{label:'执行周期',children:'2026-08-01 至 08-31'},{label:'关怀对象',children:'本月生日员工'},{label:'权益内容',children:'生日蛋糕券 ¥100'},{label:'预计预算',children:'¥3,600.00'},{label:'执行方式',children:'系统自动触发'}]}/></Card><Row gutter={[16,16]}><Col xs={24} xl={16}><Space direction="vertical" size={16} style={{width:'100%'}}><Card title="执行进度"><Flex align="center" gap={24}><Progress percent={78}/><Typography.Text type="secondary">28 / 36 人已触达</Typography.Text></Flex></Card><Card title="员工触达记录"><Table rowKey="name" pagination={false} dataSource={[{name:'张悦',department:'产品中心',notice:'已送达',benefit:'已领取',time:'08-12 09:00'},{name:'李明',department:'研发中心',notice:'已送达',benefit:'待领取',time:'08-15 09:00'},{name:'王芳',department:'营销中心',notice:'发送失败',benefit:'待发放',time:'08-16 09:00'}]} columns={[{title:'员工',dataIndex:'name'},{title:'部门',dataIndex:'department'},{title:'通知状态',dataIndex:'notice',render:value=><Tag color={value==='发送失败'?'error':'success'}>{value}</Tag>},{title:'权益状态',dataIndex:'benefit'},{title:'执行时间',dataIndex:'time'},{title:'操作',render:(_,record)=><Button type="link" disabled={record.notice!=='发送失败'}>重试</Button>}]} /></Card></Space></Col><Col xs={24} xl={8}><Card title="操作记录"><Timeline items={[{color:'blue',children:'苏然补发失败通知 · 08-16 10:20'},{children:'系统执行第三批生日关怀 · 08-16 09:00'},{children:'陈产品发布计划 · 08-01 08:30'}]}/></Card></Col></Row></div>;
}

function CareTemplates() {
  const { message } = App.useApp();
  const templates = [{title:'温暖生日祝福',type:'生日关怀',desc:'愿新一岁的每一天都充满热爱与惊喜。',icon:<GiftOutlined/>,color:'blue'},{title:'五周年同行纪念',type:'入职周年',desc:'感谢一路同行，愿我们继续共同创造美好。',icon:<HeartOutlined/>,color:'purple'},{title:'欢迎加入云悦',type:'入职欢迎',desc:'欢迎加入团队，期待与你一起开启新的旅程。',icon:<TeamOutlined/>,color:'orange'}];
  return <div className="page-stack"><ListPageHeading paths={['人文关怀','内容配置','关怀模板']} title="关怀模板" subtitle="维护不同关怀场景使用的通知内容。"/><Card><div className="table-toolbar"><Button type="primary" icon={<PlusOutlined/>} onClick={()=>message.info('Demo：打开模板弹窗')}>新建模板</Button></div><Row gutter={[16,16]}>{templates.map(item=><Col xs={24} md={12} xl={8} key={item.title}><Card hoverable className="compact-template-card"><Flex justify="space-between" align="center" gap={16}><div className="template-copy"><Typography.Text type="secondary">{item.type}</Typography.Text><Typography.Title level={4} title={item.title}>{item.title}</Typography.Title><Typography.Paragraph type="secondary" ellipsis={{rows:2}}>{item.desc}</Typography.Paragraph><Space><Button type="link" className="inline-link">预览</Button><Button type="link" className="inline-link">编辑</Button><Button type="link" className="inline-link">复制</Button></Space></div><div className={`compact-stat-logo ${item.color}`}>{item.icon}</div></Flex></Card></Col>)}</Row></Card></div>;
}

function CareRecords(){return <div className="page-stack"><ListPageHeading paths={['人文关怀','关怀运营','关怀记录']} title="关怀记录" subtitle="查询员工关怀触达与权益领取记录。"/><Card><Table rowKey="id" dataSource={[{id:1,name:'张悦',type:'生日关怀',plan:'八月员工生日关怀',notice:'已送达',benefit:'已领取',date:'2026-08-12'},{id:2,name:'王芳',type:'生日关怀',plan:'八月员工生日关怀',notice:'发送失败',benefit:'待发放',date:'2026-08-16'}]} columns={[{title:'员工',dataIndex:'name'},{title:'关怀类型',dataIndex:'type'},{title:'计划名称',dataIndex:'plan'},{title:'通知状态',dataIndex:'notice'},{title:'权益状态',dataIndex:'benefit'},{title:'执行日期',dataIndex:'date'}]}/></Card></div>}
function CareTypes(){return <div className="page-stack"><ListPageHeading paths={['人文关怀','内容配置','关怀类型']} title="关怀类型" subtitle="配置关怀类型、触发规则和启用状态。"/><Card><Table rowKey="name" dataSource={[{name:'生日关怀',trigger:'员工生日当天',status:true},{name:'入职周年',trigger:'入职日期周年',status:true},{name:'节日关怀',trigger:'指定节日日期',status:true},{name:'特殊慰问',trigger:'人工发起',status:false}]} columns={[{title:'类型名称',dataIndex:'name'},{title:'触发规则',dataIndex:'trigger'},{title:'启用状态',dataIndex:'status',render:value=><Switch checked={value}/>}]} /></Card></div>}
